from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(614, 698)
        self.ref_btn = QtWidgets.QPushButton(Form)
        self.ref_btn.setGeometry(QtCore.QRect(10, 670, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ref_btn.sizePolicy().hasHeightForWidth())
        self.ref_btn.setSizePolicy(sizePolicy)
        self.ref_btn.setObjectName("ref_btn")
        self.graphic_line = QtWidgets.QLineEdit(Form)
        self.graphic_line.setEnabled(True)
        self.graphic_line.setGeometry(QtCore.QRect(40, 590, 271, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphic_line.sizePolicy().hasHeightForWidth())
        self.graphic_line.setSizePolicy(sizePolicy)
        self.graphic_line.setObjectName("graphic_line")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 580, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 660, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.x2_line = QtWidgets.QLineEdit(Form)
        self.x2_line.setGeometry(QtCore.QRect(130, 630, 71, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x2_line.sizePolicy().hasHeightForWidth())
        self.x2_line.setSizePolicy(sizePolicy)
        self.x2_line.setObjectName("x2_line")
        self.step_line = QtWidgets.QLineEdit(Form)
        self.step_line.setGeometry(QtCore.QRect(240, 630, 71, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_line.sizePolicy().hasHeightForWidth())
        self.step_line.setSizePolicy(sizePolicy)
        self.step_line.setObjectName("step_line")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(210, 620, 27, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(110, 620, 19, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.x1_line = QtWidgets.QLineEdit(Form)
        self.x1_line.setGeometry(QtCore.QRect(30, 630, 71, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1_line.sizePolicy().hasHeightForWidth())
        self.x1_line.setSizePolicy(sizePolicy)
        self.x1_line.setObjectName("x1_line")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 620, 18, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.table = QtWidgets.QLCDNumber(Form)
        self.table.setEnabled(True)
        self.table.setGeometry(QtCore.QRect(8, 60, 594, 75))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setMinimumSize(QtCore.QSize(300, 75))
        self.table.setDigitCount(8)
        self.table.setObjectName("table")
        self.btn8 = QtWidgets.QPushButton(Form)
        self.btn8.setGeometry(QtCore.QRect(94, 314, 80, 80))
        self.btn8.setMinimumSize(QtCore.QSize(80, 80))
        self.btn8.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn8.setFont(font)
        self.btn8.setObjectName("btn8")
        self.buttonGroup_digits = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_digits.setObjectName("buttonGroup_digits")
        self.buttonGroup_digits.addButton(self.btn8)
        self.btn6 = QtWidgets.QPushButton(Form)
        self.btn6.setGeometry(QtCore.QRect(180, 228, 80, 80))
        self.btn6.setMinimumSize(QtCore.QSize(80, 80))
        self.btn6.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn6.setFont(font)
        self.btn6.setObjectName("btn6")
        self.buttonGroup_digits.addButton(self.btn6)
        self.btn_log2 = QtWidgets.QPushButton(Form)
        self.btn_log2.setGeometry(QtCore.QRect(524, 400, 80, 80))
        self.btn_log2.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_log2.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(28)
        self.btn_log2.setFont(font)
        self.btn_log2.setObjectName("btn_log2")
        self.buttonGroup_more = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_more.setObjectName("buttonGroup_more")
        self.buttonGroup_more.addButton(self.btn_log2)
        self.btn3 = QtWidgets.QPushButton(Form)
        self.btn3.setGeometry(QtCore.QRect(180, 142, 80, 80))
        self.btn3.setMinimumSize(QtCore.QSize(80, 80))
        self.btn3.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn3.setFont(font)
        self.btn3.setObjectName("btn3")
        self.buttonGroup_digits.addButton(self.btn3)
        self.btn_oct = QtWidgets.QPushButton(Form)
        self.btn_oct.setGeometry(QtCore.QRect(352, 400, 80, 80))
        self.btn_oct.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_oct.setMaximumSize(QtCore.QSize(80, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btn_oct.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_oct.setFont(font)
        self.btn_oct.setObjectName("btn_oct")
        self.buttonGroup_not = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_not.setObjectName("buttonGroup_not")
        self.buttonGroup_not.addButton(self.btn_oct)
        self.btn_clear = QtWidgets.QPushButton(Form)
        self.btn_clear.setEnabled(True)
        self.btn_clear.setGeometry(QtCore.QRect(266, 486, 80, 80))
        self.btn_clear.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_clear.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("background-color: rgb(254, 166, 43);")
        self.btn_clear.setObjectName("btn_clear")
        self.btn_bin = QtWidgets.QPushButton(Form)
        self.btn_bin.setGeometry(QtCore.QRect(352, 228, 80, 80))
        self.btn_bin.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_bin.setMaximumSize(QtCore.QSize(80, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btn_bin.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_bin.setFont(font)
        self.btn_bin.setObjectName("btn_bin")
        self.buttonGroup_not.addButton(self.btn_bin)
        self.btn_mult = QtWidgets.QPushButton(Form)
        self.btn_mult.setGeometry(QtCore.QRect(266, 314, 80, 80))
        self.btn_mult.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_mult.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_mult.setFont(font)
        self.btn_mult.setObjectName("btn_mult")
        self.buttonGroup_binary = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_binary.setObjectName("buttonGroup_binary")
        self.buttonGroup_binary.addButton(self.btn_mult)
        self.btn_pi = QtWidgets.QPushButton(Form)
        self.btn_pi.setGeometry(QtCore.QRect(438, 486, 80, 80))
        self.btn_pi.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_pi.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(28)
        self.btn_pi.setFont(font)
        self.btn_pi.setObjectName("btn_pi")
        self.btn5 = QtWidgets.QPushButton(Form)
        self.btn5.setGeometry(QtCore.QRect(94, 228, 80, 80))
        self.btn5.setMinimumSize(QtCore.QSize(80, 80))
        self.btn5.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn5.setFont(font)
        self.btn5.setObjectName("btn5")
        self.buttonGroup_digits.addButton(self.btn5)
        self.btn_hex = QtWidgets.QPushButton(Form)
        self.btn_hex.setGeometry(QtCore.QRect(352, 314, 80, 80))
        self.btn_hex.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_hex.setMaximumSize(QtCore.QSize(80, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btn_hex.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_hex.setFont(font)
        self.btn_hex.setObjectName("btn_hex")
        self.buttonGroup_not.addButton(self.btn_hex)
        self.btn_dot = QtWidgets.QPushButton(Form)
        self.btn_dot.setGeometry(QtCore.QRect(94, 400, 80, 80))
        self.btn_dot.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_dot.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_dot.setFont(font)
        self.btn_dot.setObjectName("btn_dot")
        self.btn_pow = QtWidgets.QPushButton(Form)
        self.btn_pow.setGeometry(QtCore.QRect(8, 486, 80, 80))
        self.btn_pow.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_pow.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_pow.setFont(font)
        self.btn_pow.setObjectName("btn_pow")
        self.buttonGroup_binary.addButton(self.btn_pow)
        self.btn_tg = QtWidgets.QPushButton(Form)
        self.btn_tg.setGeometry(QtCore.QRect(438, 228, 80, 80))
        self.btn_tg.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_tg.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(28)
        self.btn_tg.setFont(font)
        self.btn_tg.setObjectName("btn_tg")
        self.buttonGroup_tryg = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_tryg.setObjectName("buttonGroup_tryg")
        self.buttonGroup_tryg.addButton(self.btn_tg)
        self.btn0 = QtWidgets.QPushButton(Form)
        self.btn0.setGeometry(QtCore.QRect(8, 400, 80, 80))
        self.btn0.setMinimumSize(QtCore.QSize(80, 80))
        self.btn0.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn0.setFont(font)
        self.btn0.setObjectName("btn0")
        self.buttonGroup_digits.addButton(self.btn0)
        self.btn_ln = QtWidgets.QPushButton(Form)
        self.btn_ln.setGeometry(QtCore.QRect(524, 314, 80, 80))
        self.btn_ln.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_ln.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(28)
        self.btn_ln.setFont(font)
        self.btn_ln.setObjectName("btn_ln")
        self.buttonGroup_more.addButton(self.btn_ln)
        self.btn_log = QtWidgets.QPushButton(Form)
        self.btn_log.setGeometry(QtCore.QRect(438, 400, 80, 80))
        self.btn_log.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_log.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(28)
        self.btn_log.setFont(font)
        self.btn_log.setObjectName("btn_log")
        self.buttonGroup_more.addButton(self.btn_log)
        self.btn_e = QtWidgets.QPushButton(Form)
        self.btn_e.setGeometry(QtCore.QRect(524, 486, 80, 80))
        self.btn_e.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_e.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(28)
        self.btn_e.setFont(font)
        self.btn_e.setObjectName("btn_e")
        self.btn_minus = QtWidgets.QPushButton(Form)
        self.btn_minus.setGeometry(QtCore.QRect(266, 228, 80, 80))
        self.btn_minus.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_minus.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_minus.setFont(font)
        self.btn_minus.setObjectName("btn_minus")
        self.buttonGroup_binary.addButton(self.btn_minus)
        self.btn4 = QtWidgets.QPushButton(Form)
        self.btn4.setGeometry(QtCore.QRect(8, 228, 80, 80))
        self.btn4.setMinimumSize(QtCore.QSize(80, 80))
        self.btn4.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn4.setFont(font)
        self.btn4.setObjectName("btn4")
        self.buttonGroup_digits.addButton(self.btn4)
        self.btn2 = QtWidgets.QPushButton(Form)
        self.btn2.setGeometry(QtCore.QRect(94, 142, 80, 80))
        self.btn2.setMinimumSize(QtCore.QSize(80, 80))
        self.btn2.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn2.setFont(font)
        self.btn2.setObjectName("btn2")
        self.buttonGroup_digits.addButton(self.btn2)
        self.btn9 = QtWidgets.QPushButton(Form)
        self.btn9.setGeometry(QtCore.QRect(180, 314, 80, 80))
        self.btn9.setMinimumSize(QtCore.QSize(80, 80))
        self.btn9.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn9.setFont(font)
        self.btn9.setObjectName("btn9")
        self.buttonGroup_digits.addButton(self.btn9)
        self.btn_dec = QtWidgets.QPushButton(Form)
        self.btn_dec.setGeometry(QtCore.QRect(352, 142, 80, 80))
        self.btn_dec.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_dec.setMaximumSize(QtCore.QSize(80, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 203, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btn_dec.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_dec.setFont(font)
        self.btn_dec.setObjectName("btn_dec")
        self.buttonGroup_not.addButton(self.btn_dec)
        self.btn_rnd = QtWidgets.QPushButton(Form)
        self.btn_rnd.setGeometry(QtCore.QRect(438, 314, 80, 80))
        self.btn_rnd.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_rnd.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(28)
        self.btn_rnd.setFont(font)
        self.btn_rnd.setObjectName("btn_rnd")
        self.buttonGroup_more.addButton(self.btn_rnd)
        self.btn_plus = QtWidgets.QPushButton(Form)
        self.btn_plus.setGeometry(QtCore.QRect(266, 142, 80, 80))
        self.btn_plus.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_plus.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_plus.setFont(font)
        self.btn_plus.setObjectName("btn_plus")
        self.buttonGroup_binary.addButton(self.btn_plus)
        self.btn1 = QtWidgets.QPushButton(Form)
        self.btn1.setGeometry(QtCore.QRect(8, 142, 80, 80))
        self.btn1.setMinimumSize(QtCore.QSize(80, 80))
        self.btn1.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn1.setFont(font)
        self.btn1.setObjectName("btn1")
        self.buttonGroup_digits.addButton(self.btn1)
        self.btn_sqrt = QtWidgets.QPushButton(Form)
        self.btn_sqrt.setGeometry(QtCore.QRect(94, 486, 80, 80))
        self.btn_sqrt.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_sqrt.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_sqrt.setFont(font)
        self.btn_sqrt.setObjectName("btn_sqrt")
        self.btn_eq = QtWidgets.QPushButton(Form)
        self.btn_eq.setGeometry(QtCore.QRect(180, 400, 80, 80))
        self.btn_eq.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_eq.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_eq.setFont(font)
        self.btn_eq.setObjectName("btn_eq")
        self.btn_ctg = QtWidgets.QPushButton(Form)
        self.btn_ctg.setGeometry(QtCore.QRect(524, 228, 80, 80))
        self.btn_ctg.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_ctg.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(28)
        self.btn_ctg.setFont(font)
        self.btn_ctg.setObjectName("btn_ctg")
        self.buttonGroup_tryg.addButton(self.btn_ctg)
        self.btn_cos = QtWidgets.QPushButton(Form)
        self.btn_cos.setGeometry(QtCore.QRect(524, 142, 80, 80))
        self.btn_cos.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_cos.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(28)
        self.btn_cos.setFont(font)
        self.btn_cos.setObjectName("btn_cos")
        self.buttonGroup_tryg.addButton(self.btn_cos)
        self.btn_sin = QtWidgets.QPushButton(Form)
        self.btn_sin.setGeometry(QtCore.QRect(438, 142, 80, 80))
        self.btn_sin.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_sin.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(28)
        self.btn_sin.setFont(font)
        self.btn_sin.setObjectName("btn_sin")
        self.buttonGroup_tryg.addButton(self.btn_sin)
        self.btn_div = QtWidgets.QPushButton(Form)
        self.btn_div.setGeometry(QtCore.QRect(266, 400, 80, 80))
        self.btn_div.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_div.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_div.setFont(font)
        self.btn_div.setObjectName("btn_div")
        self.buttonGroup_binary.addButton(self.btn_div)
        self.btn_clear_s = QtWidgets.QPushButton(Form)
        self.btn_clear_s.setEnabled(True)
        self.btn_clear_s.setGeometry(QtCore.QRect(180, 486, 80, 80))
        self.btn_clear_s.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_clear_s.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_clear_s.setFont(font)
        self.btn_clear_s.setStyleSheet("background-color: rgb(224, 196, 13);")
        self.btn_clear_s.setObjectName("btn_clear_s")
        self.btn7 = QtWidgets.QPushButton(Form)
        self.btn7.setGeometry(QtCore.QRect(8, 314, 80, 80))
        self.btn7.setMinimumSize(QtCore.QSize(80, 80))
        self.btn7.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn7.setFont(font)
        self.btn7.setObjectName("btn7")
        self.buttonGroup_digits.addButton(self.btn7)
        self.btn_fact = QtWidgets.QPushButton(Form)
        self.btn_fact.setGeometry(QtCore.QRect(352, 486, 80, 80))
        self.btn_fact.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_fact.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        self.btn_fact.setFont(font)
        self.btn_fact.setObjectName("btn_fact")
        self.calc_combo = QtWidgets.QComboBox(Form)
        self.calc_combo.setGeometry(QtCore.QRect(147, 15, 184, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calc_combo.setFont(font)
        self.calc_combo.setObjectName("calc_combo")
        self.calc_combo.addItem("")
        self.calc_combo.addItem("")
        self.beta_btn = QtWidgets.QCheckBox(Form)
        self.beta_btn.setGeometry(QtCore.QRect(7, 30, 130, 17))
        self.beta_btn.setObjectName("beta_btn")
        self.graphics_btn = QtWidgets.QCheckBox(Form)
        self.graphics_btn.setGeometry(QtCore.QRect(7, 4, 135, 17))
        self.graphics_btn.setObjectName("graphics_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Продвинутый калькулятор"))
        self.ref_btn.setText(_translate("Form", "справка"))
        self.label.setText(_translate("Form", "y="))
        self.pushButton_2.setText(_translate("Form", "построить"))
        self.label_4.setText(_translate("Form", "шаг:"))
        self.label_3.setText(_translate("Form", "до:"))
        self.label_2.setText(_translate("Form", "от:"))
        self.btn8.setText(_translate("Form", "8"))
        self.btn6.setText(_translate("Form", "6"))
        self.btn_log2.setText(_translate("Form", "log2"))
        self.btn3.setText(_translate("Form", "3"))
        self.btn_oct.setText(_translate("Form", "oct"))
        self.btn_clear.setText(_translate("Form", "С"))
        self.btn_bin.setText(_translate("Form", "bin"))
        self.btn_mult.setText(_translate("Form", "*"))
        self.btn_pi.setText(_translate("Form", "pi"))
        self.btn5.setText(_translate("Form", "5"))
        self.btn_hex.setText(_translate("Form", "hex"))
        self.btn_dot.setText(_translate("Form", "."))
        self.btn_pow.setText(_translate("Form", "^"))
        self.btn_tg.setText(_translate("Form", "tg"))
        self.btn0.setText(_translate("Form", "0"))
        self.btn_ln.setText(_translate("Form", "ln"))
        self.btn_log.setText(_translate("Form", "log"))
        self.btn_e.setText(_translate("Form", "e"))
        self.btn_minus.setText(_translate("Form", "-"))
        self.btn4.setText(_translate("Form", "4"))
        self.btn2.setText(_translate("Form", "2"))
        self.btn9.setText(_translate("Form", "9"))
        self.btn_dec.setText(_translate("Form", "dec"))
        self.btn_rnd.setText(_translate("Form", "rnd"))
        self.btn_plus.setText(_translate("Form", "+"))
        self.btn1.setText(_translate("Form", "1"))
        self.btn_sqrt.setText(_translate("Form", "√"))
        self.btn_eq.setText(_translate("Form", "="))
        self.btn_ctg.setText(_translate("Form", "ctg"))
        self.btn_cos.setText(_translate("Form", "cos"))
        self.btn_sin.setText(_translate("Form", "sin"))
        self.btn_div.setText(_translate("Form", "/"))
        self.btn_clear_s.setText(_translate("Form", "CE"))
        self.btn7.setText(_translate("Form", "7"))
        self.btn_fact.setText(_translate("Form", "!"))
        self.calc_combo.setItemText(0, _translate("Form", "обычный калькулятор"))
        self.calc_combo.setItemText(1, _translate("Form", "расширенный калькулятор"))
        self.beta_btn.setText(_translate("Form", "Простой калькулятор"))
        self.graphics_btn.setText(_translate("Form", "Построение графиков"))
